In [17]:
#Pour créer un tableau on utilise la fonction qu'on appelle arrays elle prend des listes#
import numpy as np

In [18]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
sous_tableau=notre_tableau[0:5]
print(sous_tableau)

[1 2 3 4 5]


In [20]:
print(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
#notion de copie#
sous_tableau=notre_tableau[0:5].copy()
print(sous_tableau)

[1 2 3 4 5]


In [22]:
sous_tableau[0]=10
print(sous_tableau)

[10  2  3  4  5]


In [23]:
print(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [24]:
mon_tableau_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_tableau_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
mon_tableau_bidimensionnel[1,2]


np.int64(6)

In [26]:
#afficher les elements de la première colonne#
mon_tableau_bidimensionnel[:,0]

array([1, 4, 7])

In [27]:
mon_tableau_bidimensionnel[0,:]

array([1, 2, 3])

In [29]:
mon_tableau_bidimensionnel[:,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [31]:
mon_tableau_bidimensionnel[:,1:-1]

array([[2],
       [5],
       [8]])

In [32]:
mon_tableau_bidimensionnel[2,1:-1]

array([8])

In [34]:
#Explorer et filtrer un array: Création d'un tableau bidimensionnel avec la fonction randint()#
array=np.random.randint(100,size=(6,4))
print(array)


[[ 8 27 56 89]
 [84 77 63 43]
 [32 52  9 53]
 [ 9 56 92 79]
 [84 55  2 99]
 [93 20 85 30]]


In [35]:
#les attributs:c'est une caractéristique ou une propriété qui décrit un objet ,une entité ou une donnée#
#ndim:permet de connaitre la dimension d'un tableau#
array.ndim

2

In [36]:
#shape:permet de connaitre le nombre de dimension qu'il y'a dans notre tableau#
array.shape

(6, 4)

In [ ]:
#dtype: permet de connaitre le type de données de notre tableau#
array.dtype

dtype('int32')

In [38]:
#size :permet de connaitre la taille de notre tableau#
array.size

24

In [39]:
#Filtrer un tableau#
#pour afficher l'ensemble des valeurs avec les opérateurs relationels <> ou != on fait:#
array[array>50]


array([56, 89, 84, 77, 63, 52, 53, 56, 92, 79, 84, 55, 99, 93, 85],
      dtype=int32)

In [40]:
array[array<50]

array([ 8, 27, 43, 32,  9,  9,  2, 20, 30], dtype=int32)

In [41]:
array[array!=50]

array([ 8, 27, 56, 89, 84, 77, 63, 43, 32, 52,  9, 53,  9, 56, 92, 79, 84,
       55,  2, 99, 93, 20, 85, 30], dtype=int32)

In [42]:
#les opérateurs and(&);or(|)#
array[(array >=50) & (array<=70) ]

array([56, 63, 52, 53, 56, 55], dtype=int32)

In [44]:
array[(array>=50) | (array<=40)]

array([ 8, 27, 56, 89, 84, 77, 63, 32, 52,  9, 53,  9, 56, 92, 79, 84, 55,
        2, 99, 93, 20, 85, 30], dtype=int32)

In [ ]:
#Concaténation ou la jointure des arrays avec numpy:on lui donne un tuple ou une liste d'array#
#La fonction concatenate permet de joindre les tableau de meme dimension#
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[2,5,6],[9,10,11],[5,6,9]])
array3=np.array([[4,10,13],[7,14,15],[10,16,84]])
np.concatenate([array1,array2,array3])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 84]])

In [47]:
#la fonction vstack permet de faire une jointure horizontale en créant un tableau unidimensionnel#
array1=np.array([15,16,47])
print(array1)

[15 16 47]


In [48]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
np.vstack([array1,array2])

array([[15, 16, 47],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [51]:
array1=np.array([[15],[16],[47]])
print(array1)

[[15]
 [16]
 [47]]


In [ ]:
#La fonction permet de faire une empilation vertical en créant un tableau bidimensionnel#
np.hstack([array1,array2])

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

In [53]:
#Fonction split#
array=np.array([15,16,17,12,49,52,12,14,36])

In [54]:
len(array)

9

In [55]:
np.split(array,[2,6])

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [56]:
array1,array2,array3=np.split(array,[2,6])
print(array1,array2,array3)

[15 16] [17 12 49 52] [12 14 36]


In [2]:
import numpy as np

In [3]:
array=np.random.randint(350, size=(10,9))
print(array)

[[153 345 115 169  68  71 129 264 238]
 [315 297  35 117 230 247 159 226 319]
 [ 93  15  70 317  99  19 146 280  58]
 [ 65  86  24 324 209 175 248 174 196]
 [100 245  75 249 239 313  74 198 142]
 [246  78 316 183 121  44  49 127  34]
 [ 39 197 225 170 241 211 183 343 178]
 [342 268 322 282 308 223 149 100  10]
 [ 89 343 183 118 206  52 139 243 116]
 [ 66  50  78 230 172 280 154 119  10]]


In [4]:
array +2

array([[155, 347, 117, 171,  70,  73, 131, 266, 240],
       [317, 299,  37, 119, 232, 249, 161, 228, 321],
       [ 95,  17,  72, 319, 101,  21, 148, 282,  60],
       [ 67,  88,  26, 326, 211, 177, 250, 176, 198],
       [102, 247,  77, 251, 241, 315,  76, 200, 144],
       [248,  80, 318, 185, 123,  46,  51, 129,  36],
       [ 41, 199, 227, 172, 243, 213, 185, 345, 180],
       [344, 270, 324, 284, 310, 225, 151, 102,  12],
       [ 91, 345, 185, 120, 208,  54, 141, 245, 118],
       [ 68,  52,  80, 232, 174, 282, 156, 121,  12]], dtype=int32)

In [5]:
array*10

array([[1530, 3450, 1150, 1690,  680,  710, 1290, 2640, 2380],
       [3150, 2970,  350, 1170, 2300, 2470, 1590, 2260, 3190],
       [ 930,  150,  700, 3170,  990,  190, 1460, 2800,  580],
       [ 650,  860,  240, 3240, 2090, 1750, 2480, 1740, 1960],
       [1000, 2450,  750, 2490, 2390, 3130,  740, 1980, 1420],
       [2460,  780, 3160, 1830, 1210,  440,  490, 1270,  340],
       [ 390, 1970, 2250, 1700, 2410, 2110, 1830, 3430, 1780],
       [3420, 2680, 3220, 2820, 3080, 2230, 1490, 1000,  100],
       [ 890, 3430, 1830, 1180, 2060,  520, 1390, 2430, 1160],
       [ 660,  500,  780, 2300, 1720, 2800, 1540, 1190,  100]],
      dtype=int32)

In [6]:
array[:,0]*10

array([1530, 3150,  930,  650, 1000, 2460,  390, 3420,  890,  660],
      dtype=int32)

In [7]:
array /2

array([[ 76.5, 172.5,  57.5,  84.5,  34. ,  35.5,  64.5, 132. , 119. ],
       [157.5, 148.5,  17.5,  58.5, 115. , 123.5,  79.5, 113. , 159.5],
       [ 46.5,   7.5,  35. , 158.5,  49.5,   9.5,  73. , 140. ,  29. ],
       [ 32.5,  43. ,  12. , 162. , 104.5,  87.5, 124. ,  87. ,  98. ],
       [ 50. , 122.5,  37.5, 124.5, 119.5, 156.5,  37. ,  99. ,  71. ],
       [123. ,  39. , 158. ,  91.5,  60.5,  22. ,  24.5,  63.5,  17. ],
       [ 19.5,  98.5, 112.5,  85. , 120.5, 105.5,  91.5, 171.5,  89. ],
       [171. , 134. , 161. , 141. , 154. , 111.5,  74.5,  50. ,   5. ],
       [ 44.5, 171.5,  91.5,  59. , 103. ,  26. ,  69.5, 121.5,  58. ],
       [ 33. ,  25. ,  39. , 115. ,  86. , 140. ,  77. ,  59.5,   5. ]])

In [8]:
np.add(array,2)

array([[155, 347, 117, 171,  70,  73, 131, 266, 240],
       [317, 299,  37, 119, 232, 249, 161, 228, 321],
       [ 95,  17,  72, 319, 101,  21, 148, 282,  60],
       [ 67,  88,  26, 326, 211, 177, 250, 176, 198],
       [102, 247,  77, 251, 241, 315,  76, 200, 144],
       [248,  80, 318, 185, 123,  46,  51, 129,  36],
       [ 41, 199, 227, 172, 243, 213, 185, 345, 180],
       [344, 270, 324, 284, 310, 225, 151, 102,  12],
       [ 91, 345, 185, 120, 208,  54, 141, 245, 118],
       [ 68,  52,  80, 232, 174, 282, 156, 121,  12]], dtype=int32)

In [9]:
np.subtract(array,7)

array([[146, 338, 108, 162,  61,  64, 122, 257, 231],
       [308, 290,  28, 110, 223, 240, 152, 219, 312],
       [ 86,   8,  63, 310,  92,  12, 139, 273,  51],
       [ 58,  79,  17, 317, 202, 168, 241, 167, 189],
       [ 93, 238,  68, 242, 232, 306,  67, 191, 135],
       [239,  71, 309, 176, 114,  37,  42, 120,  27],
       [ 32, 190, 218, 163, 234, 204, 176, 336, 171],
       [335, 261, 315, 275, 301, 216, 142,  93,   3],
       [ 82, 336, 176, 111, 199,  45, 132, 236, 109],
       [ 59,  43,  71, 223, 165, 273, 147, 112,   3]], dtype=int32)

In [10]:
np.multiply(array,10)

array([[1530, 3450, 1150, 1690,  680,  710, 1290, 2640, 2380],
       [3150, 2970,  350, 1170, 2300, 2470, 1590, 2260, 3190],
       [ 930,  150,  700, 3170,  990,  190, 1460, 2800,  580],
       [ 650,  860,  240, 3240, 2090, 1750, 2480, 1740, 1960],
       [1000, 2450,  750, 2490, 2390, 3130,  740, 1980, 1420],
       [2460,  780, 3160, 1830, 1210,  440,  490, 1270,  340],
       [ 390, 1970, 2250, 1700, 2410, 2110, 1830, 3430, 1780],
       [3420, 2680, 3220, 2820, 3080, 2230, 1490, 1000,  100],
       [ 890, 3430, 1830, 1180, 2060,  520, 1390, 2430, 1160],
       [ 660,  500,  780, 2300, 1720, 2800, 1540, 1190,  100]],
      dtype=int32)

In [11]:
np.divide(array,50)

array([[3.06, 6.9 , 2.3 , 3.38, 1.36, 1.42, 2.58, 5.28, 4.76],
       [6.3 , 5.94, 0.7 , 2.34, 4.6 , 4.94, 3.18, 4.52, 6.38],
       [1.86, 0.3 , 1.4 , 6.34, 1.98, 0.38, 2.92, 5.6 , 1.16],
       [1.3 , 1.72, 0.48, 6.48, 4.18, 3.5 , 4.96, 3.48, 3.92],
       [2.  , 4.9 , 1.5 , 4.98, 4.78, 6.26, 1.48, 3.96, 2.84],
       [4.92, 1.56, 6.32, 3.66, 2.42, 0.88, 0.98, 2.54, 0.68],
       [0.78, 3.94, 4.5 , 3.4 , 4.82, 4.22, 3.66, 6.86, 3.56],
       [6.84, 5.36, 6.44, 5.64, 6.16, 4.46, 2.98, 2.  , 0.2 ],
       [1.78, 6.86, 3.66, 2.36, 4.12, 1.04, 2.78, 4.86, 2.32],
       [1.32, 1.  , 1.56, 4.6 , 3.44, 5.6 , 3.08, 2.38, 0.2 ]])

In [12]:
np.mean(array)

np.float64(170.74444444444444)

In [13]:
array.mean(axis=0)

array([150.8, 192.4, 144.3, 215.9, 189.3, 163.5, 143. , 207.4, 130.1])

In [14]:
np.mean(array, axis=0)

array([150.8, 192.4, 144.3, 215.9, 189.3, 163.5, 143. , 207.4, 130.1])

In [15]:
np.mean(array,axis=1)

array([172.44444444, 216.11111111, 121.88888889, 166.77777778,
       181.66666667, 133.11111111, 198.55555556, 222.66666667,
       165.44444444, 128.77777778])

In [30]:
#la fonction genfromtxt permet d'importer les fichiers csv# 
houses=np.genfromtxt("Houses.csv" , delimiter=",", dtype=int )
print(houses)


[[212000   4148  25264]
 [230000   2501  11891]
 [339000   4374  25351]
 [289000   2398  22215]
 [160000   2536   9234]
 [ 85000   2368  13329]
 [ 85000   1264   8407]
 [145000   1572  12588]
 [164000   2375  16204]
 [123500   1161   9626]
 [180000   1542   8755]
 [159500   1464  14636]
 [156000   2240  21780]
 [146500   1269  11250]
 [101500    924   7361]
 [109800    768  10497]
 [182000   1320  15768]
 [110000   1845  12153]
 [125000   1274  13634]
 [ 80000   1905  10890]]


In [31]:
houses[:,0]=houses[:,0]*0.86
print(houses)

[[182320   4148  25264]
 [197800   2501  11891]
 [291540   4374  25351]
 [248540   2398  22215]
 [137600   2536   9234]
 [ 73100   2368  13329]
 [ 73100   1264   8407]
 [124700   1572  12588]
 [141040   2375  16204]
 [106210   1161   9626]
 [154800   1542   8755]
 [137170   1464  14636]
 [134160   2240  21780]
 [125990   1269  11250]
 [ 87290    924   7361]
 [ 94428    768  10497]
 [156520   1320  15768]
 [ 94600   1845  12153]
 [107500   1274  13634]
 [ 68800   1905  10890]]


In [32]:
houses[:,1:]=houses[:,1:]*0.09
print(houses)


[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [33]:
len(houses[houses[:,2]>1000])

13